version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Altere para uma senha segura!
      MYSQL_DATABASE: mydatabase        # Database criada automaticamente
      MYSQL_USER: myuser                 # Usuário opcional
      MYSQL_PASSWORD: mypassword         # Senha do usuário
    ports:
      - "3306:3306"                      # Porta padrão do MySQL
    volumes:
      - mysql_data:/var/lib/mysql        # Persistência de dados
    restart: unless-stopped
    networks:
      - mysql_net

  adminer:
    image: adminer
    container_name: adminer_container
    restart: unless-stopped
    ports:
      - "8081:8080"                      # Adminer na porta 8081 (externo:interno)
    depends_on:
      - mysql
    networks:
      - mysql_net

volumes:
  mysql_data:

networks:
  mysql_net:
    driver: bridge